language: php
php:
  - "5.6"

before_install:
    - sudo apt-get update > /dev/null

install:
    # Install composer dependencies
    - cd $TRAVIS_BUILD_DIR && composer self-update
    - cd $TRAVIS_BUILD_DIR && composer install --dev --no-interaction --optimize-autoloader

cache:
    # Cache composer packages
    apt: true
    directories:
        - $HOME/.composer

before_script:
    # Prepare cache folders
    - cd $TRAVIS_BUILD_DIR && rm -Rf app/cache/*
    - cd $TRAVIS_BUILD_DIR && rm -Rf app/logs/*
    - cd $TRAVIS_BUILD_DIR && chmod -R 777 app/cache
    - cd $TRAVIS_BUILD_DIR && chmod -R 777 app/logs

branches:
  only:
    - master
    - develop
    - /^SGFD-.*$/
    - /^hotfix\/.*$/